# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
liberapay: biter777
ko_fi: biter777
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: countries
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://www.buymeacoffee.com/CAhuDKg', 'https://money.yandex.ru/to/4100164702007', 'https://pay.cloudtips.ru/p/94fc4268'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
